language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 0.7
  - 1.0
  - 1.2
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
